Feat/login : 로그인, 회원가입 화면
juseonghyun/nbc_sns pull request #11
Opened 2024-04-03 10:31 UTC by koreabgj

수고 많으십니다.
누락된 기능이나 개선할 부분이 있는지 검토 부탁드립니다.

2024-04-03 11:58 UTC, DoTheBestMayB requested changes

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/AndroidManifest.xml
> +        </activity>
앱의 진입점을 변경해서 구현하신 점👍
다만, 구현이 끝나면 원래대로 수정해주세요.

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/Comment.kt
댓글은 구현하지 않기로 했으므로, Comment 관련 코드와 파일은 지워주세요.

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/LogInActiviy.kt
파일 이름이 클래스와 다릅니다.
LogInActivity 에서 "t"가 누락됐습니다.

또한 login package를 만들어서, 해당 패키지로 옮겨주세요.

2024-04-03 11:58 UTC, DoTheBestMayB commented on build.gradle.kts
gradle version을 사전에 정해서 모두가 같은 버전을 사용해야 했었는데 놓쳤네요.

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/LogInActiviy.kt
> +            isEnglish = !isEnglish
한영을 나타내는 변수가 람다 block 내부에 선언되어 있습니다. 그래서 isEnglish는 항상 true가 됩니다.

아래 키워드로 검색해서 변수의 scope에 대해 학습하신 후 수정해주세요.
block scope of a variable

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/LogInActiviy.kt
> +            intent.getStringExtra("pw") ?: ""
intent를 전달하는 곳이 없기 때문에, 이 코드는 불필요합니다.

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/UserManager.kt
이 클래스는 삭제하시고, ui 패키지 아래에 있는 UserManager를 사용해주세요.

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/LogInActiviy.kt
> +                }
UserManager 함수를 이용해 간접적으로 데이터를 가져오도록 수정해주세요.

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/RegisterActivity.kt
register 패키지를 만들고, 해당 패키지로 클래스 파일을 옮겨주세요.

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/RegisterActivity.kt
> +            isEnglish = !isEnglish
이 변수 또한 block scope에 대해 학습하신 후 수정해주세요.

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/RegisterActivity.kt
> +                    )
닉네임 사용이 누락됐습니다.

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/RegisterActivity.kt
> +                        finish()
startActivity 대신 finish만 호출하면 될 것 같습니다.
finish 과정에서 id와 pw를 HomeActivity에 전달하려면 어떻게 바꿔야 할까요?

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/RegisterActivity.kt
> +            }
사용하지 않는 함수는 지워주세요.

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/UserInfo.kt
이 클래스는 지워주세요.

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/res/drawable/dice_5.png
사용하지 않는 파일은 지워주세요.

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/res/layout/activity_log_in.xml
> +        android:src="@drawable/team_logo"
team_logo 대신 인스타그램 로고로 변경해주시면 좋을 것 같습니다.

2024-04-03 11:58 UTC, DoTheBestMayB commented on app/src/main/res/layout/activity_register.xml
> +    android:background="#87CEEB"
배경색 설정은 지워주세요.

2024-04-03 12:24 UTC, juseonghyun commented on app/src/main/AndroidManifest.xml
> +        </activity>
추가로 MainActivity로 바꿔주시면 되겠습니다!

2024-04-03 12:31 UTC, juseonghyun requested changes
종성님께서 코드리뷰 잘 해주신것같습니다!
특히, 댓글기능 관련된건 전부 사용하지 않기로했으니 Comment 관련 코드와 파일은 꼭 삭제 해주셔야합니다!

var isEnglish = false
isEnglish = !isEnglis 
이 부분 모르겠다면 저한테 찾아와주세요!

2024-04-03 13:13 UTC, DoTheBestMayB requested changes

2024-04-03 13:13 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/login/LogInActivity.kt
>              isEnglish = !isEnglish
관련 내용을 먼저 학습하시고 수정해주세요.

2024-04-03 13:13 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/login/LogInActivity.kt
> +            }
1. 람다 block 내부에 함수를 선언할 일은 많지 않으며, 현재 로직에서도 불필요합니다.
2. 코드상에서 에러가 나왔을 때, IDE 힌트를 이용해 자동으로 코드를 생성하지 마시고, 오류가 왜 났는지 기존의 코드 로직을 분석해서 직접 수정해주세요.
3. commit 하기 전에 수정된 코드가 정상적으로 동작하는지 에뮬레이터에서 확인해주세요.

2024-04-03 13:13 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/login/RegisterActivity.kt
> +                    )
사용자에게 입력 받은 별명을 사용하지 않고 빈 값을 입력하고 있으며, 이전 리뷰에서 말씀드렸지만 수정이 되지 않았습니다.
https://github.com/juseonghyun/nbc_sns/pull/11#discussion_r1549582754

merge를 위해서 빨리 수정하시지 않아도 됩니다. 제가 드린 코멘트에 대해 기존 로직과 수정을 위한 학습을 먼저하신 후 수정해주세요.

2024-04-03 13:13 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/login/RegisterActivity.kt
> +                        finish()
이 부분도 이전 리뷰에서 수정을 요청드렸는데, 아직 반영이 되지 않았습니다.

2024-04-03 14:09 UTC, koreabgj commented on app/src/main/java/com/example/nbc_sns/login/LogInActivity.kt
>              isEnglish = !isEnglish
충분히 이해했고 잘 구현되는 것을 확인했습니다.

2024-04-03 15:27 UTC, DoTheBestMayB commented on app/src/main/java/com/example/nbc_sns/login/LogInActivity.kt
>              isEnglish = !isEnglish
수정하시기 전 isEnlgish는 lambda block(setOnClickListener  함수의 { } 블록 내부)의 local variable 입니다. lambda block 내부에 있는 변수는 lambda block이 종료되면 참조하는 변수가 없기 때문에 GC(메모리에 있는 데이터를 지우는 역할)에 의해 데이터가 삭제 됩니다.

수정하신 isEnglish 변수는 onCreate 함수의 local variable 입니다. Java에서 람다 블록은 final이 아닌 local variable에 접근할 수 없습니다.

![image](https://github.com/juseonghyun/nbc_sns/assets/48354989/009edd70-ddfb-4feb-ada2-d78783d2b19b)


그러면 왜 Kotlin으로 작성한 현재 코드에서는 잘 동작하는 걸까요? Java로 디컴파일 된 코드를 확인해보면 boolean 변수인 isEnglish가 final 클래스로 wrapping되도록 수정된 것을 볼 수 있습니다.

![image](https://github.com/juseonghyun/nbc_sns/assets/48354989/ddca3dab-2c96-4999-ab0a-f295f464c7b1)
![image](https://github.com/juseonghyun/nbc_sns/assets/48354989/c5e34772-3af3-4e5c-ab1f-a911037d155c)


알고 사용하는 것과 모르고 사용하는 것은 차이가 큽니다.
local variable이 아닌 member variable에 접근하는 것이 더 일반적이며, Kotlin 컴파일러가 자동으로 변환해줘서 잘 동작할지라도 일반적인 방법을 사용하는 것이 좋습니다.

2024-04-04 09:56 UTC, koreabgj commented on app/src/main/java/com/example/nbc_sns/login/LogInActivity.kt
>              isEnglish = !isEnglish
설명 감사합니다만 이해하기 어렵습니다. 지금은 심화 또는 최종 프로젝트가 아니라는 것을 알아주셨으면 좋겠습니다.

2024-04-05 03:52 UTC, bora44144 approved these changes

2024-04-05 05:56 UTC, DoTheBestMayB approved these changes
수고하셨습니다 👍👍👍👍👍

2024-04-05 05:57 UTC, juseonghyun approved these changes
수고하셨습니다!

2024-04-05 05:58 UTC, merged